### ISSUE TITLE
What website should accomplish

### ISSUE THREAD

**Issue by helenvholmes** [wgxcodersdc/old-website#1]
I'm going to spew out what I think it should do, and then I'd like to hear what you guys think I'm missing or should be different.
# Hairier Problems

**We should rethink forums.** How useful are the forums? Seemed like they were and then their usefulness dropped off. Is there a better way to allow people a platform to create study groups? What are the logistics for that when groups need to find spaces? Do we suggest they find spaces on their own? Do we have people fill out a form to contact us when they want to make a new meet up group?

**Files from Panels.** We generate code from workshops and we need good places to put that stuff. I think this stuff should live on [Github](https://github.com/womenwhocodedc) and in [Gists](https://gist.github.com/) but it's important that whatever we decide we stick to it.

Next going from highest to lowest priority:
# More Straightforward Suggestions

**We should use the [Meetup API](http://www.meetup.com/meetup_api/) for event handling.** I don't think we should stop using Meetups since it handles event RSVPs really well. We will also slowly gain users through them. That said, I think that we should have one point of contact: our website. ("Need _x_? Go to womenwhocodedc.com!") The ideal would be that admins could create events through our CMS and events would be listed on our site. (Looking through the docs that should be possible.)

**We need a volunteer board for WWCode.** I'm imagining event leads and whatever other positions we might need to fill eventually. I know that we can't scale up if we don't delegate tasks more, which means we need more overall people.

**We need a contact form.** Who knows who we haven't reached because they haven't had our emails, y'know?

**We need resource pages.** I think we could structure these by language, and within a language, from complete beginner through advanced, perhaps. I think we should really pare down the overall number of suggestions as to not inundate people with resources. (Not languages, but I think should be included: tools, theory.)

**We need a sponsors area.** I think we should have an area to list sponsors with a big ol' call-to-action button to make other organizations become sponsors.

**We could have a member highlight section.** I love member highlights, and I think it would be nice to have a photo of our member, who they are, what they've accomplished, etc. Being featured is an accomplishment people could even list on resumes, potentially, if we did it based entirely on merit and not based on having to meet a number every month. Food for thought.

**We need an about page.** I'm imagining a place for the WWCode Mission Statement and some stuff about our chapter in particular.

**We should have a job board.** This I think is useful and should be carried over.

**We should have a place for our talks.** Do people agree with this?

**We should be able to have photos.** Photos I think add personality. I think that maybe we could use Flickr for this, and that way people could upload their own photos and tag us when it's relevant, or something like that. Alternatively, we could go all-Instagram with a hashtag, since it's what's in vogue. What do you think?

**Press kit.** If we continue to grow as a chapter, having assets like our logo, some photos, etc. put together would be nice.
# More Future-y Type Things

**We might consider implementing a store.** I think it'd be fun to generate/buy some WWCode swag. Proceeds from the sales could go toward the organization for food and events.
# Non-Site

**Tone guides for content creators.** We have guideline docs for  code styles. I think having one for content/site admins so make sure that when people write about things on the website would be nice.

**We need to delegate content creation.** Heh heh heh, need some volunteers first of course. U mad bro?

**We should consider filming our talks.** I think that without filming them, it's sort of silly to put the lectures up online. What do you think?

Phew. That was a lot. I'm going to use all of this to inform my wireframes (think I'm going to just jump in to that) but please make any suggestions that you think will better the site.

**Comment by kgibilterra** [comment]
So I didn't want to mess with any of the above, but a few comments

<b>Ideal State</b>
We connect up with womenwhocode.com and figure out some sort of way that people can be in charge of the international organization, but then network organizers can be in charge of their chapter page (dc.womenwhocode.com, etc)

That being said, I think the MVP for a chapter page should be something that could be easily set up so that we could have a page for each chapter without someone having to be dedicated to it.

<b>Potential MVP:</b>
"About Our Chapter"
"Contact Us" (could be form, could be email)
"Event Handling" (if this is automatic through meetup where we can create/edit/show events, that would be awesome)

Then I think we could look at the rest as involving more touch from the organizers. So adding/removing sponsors, having some sort of communication tool for study groups, volunteers, etc.

I think that forums is a super interesting concept, but we should save that for after getting most other things completed (or maybe for the hackathon). I'm really interested in how we can help with communication, but I think that's the hardest thing out of everything we  have.

I'll sketch out some ideas for the MVP so I can show them to you tomorrow Helen! And I'll talk to the SF team to see if they're for/against the dc.womenwhocode.com idea - hopefully not. If they're down to look into it, we can have a meeting together with our MVP concept!

And I can help more with content since I'm like MEH with website development haha. Also I know jack shit about CMS systems - I was always hardcore "if you haven't coded the website from scratch, you haven't really done anything" in college. I now realize that isn't true, buuutttt due to this my "website management" ideas are very limited.

**Comment by helenvholmes** [comment]
I was thinking currently that to handle starting new groups should also just be a form. I was thinking that our part of the equation could be just setting them up as defaulting to current event host and then helping them find a place to meet up, get their first event out on the schedule. Best way to actually get new study groups happening, I think. This will also eliminate forums, I think, and other noise.

We shouldn't build our own CMS from scratch. I'm oscillating on whether or not Craft is the best for the job (it might not be) but we definitely shouldn't be writing our own.
